-- Apply GL classification to account_mappings (run AFTER migration and AFTER you confirm the mapping).
-- Updates statement_type and reporting_category for all 90 GL codes.

UPDATE account_mappings am
SET
  statement_type   = v.statement_type,
  reporting_category = v.reporting_category,
  updated_at       = now()
FROM (VALUES
  ('090', 'balance_sheet', 'Cash & Bank'),
  ('091', 'balance_sheet', 'Cash & Bank'),
  ('200', 'profit_and_loss', 'Revenue'),
  ('260', 'profit_and_loss', 'Revenue'),
  ('270', 'profit_and_loss', 'Revenue'),
  ('300', 'profit_and_loss', 'Cost of Sales'),
  ('310', 'profit_and_loss', 'Cost of Sales'),
  ('320', 'profit_and_loss', 'Cost of Sales'),
  ('325', 'profit_and_loss', 'Cost of Sales'),
  ('400', 'profit_and_loss', 'Marketing & Sales'),
  ('401', 'profit_and_loss', 'Professional Fees'),
  ('404', 'profit_and_loss', 'General & Administrative'),
  ('408', 'profit_and_loss', 'General & Administrative'),
  ('412', 'profit_and_loss', 'Professional Fees'),
  ('416', 'profit_and_loss', 'General & Administrative'),
  ('418', 'profit_and_loss', 'General & Administrative'),
  ('420', 'profit_and_loss', 'General & Administrative'),
  ('424', 'profit_and_loss', 'General & Administrative'),
  ('425', 'profit_and_loss', 'General & Administrative'),
  ('429', 'profit_and_loss', 'General & Administrative'),
  ('433', 'profit_and_loss', 'General & Administrative'),
  ('437', 'profit_and_loss', 'General & Administrative'),
  ('441', 'profit_and_loss', 'Professional Fees'),
  ('445', 'profit_and_loss', 'Technology & Infrastructure'),
  ('449', 'profit_and_loss', 'General & Administrative'),
  ('457', 'profit_and_loss', 'General & Administrative'),
  ('461', 'profit_and_loss', 'General & Administrative'),
  ('463', 'profit_and_loss', 'Technology & Infrastructure'),
  ('465', 'profit_and_loss', 'General & Administrative'),
  ('469', 'profit_and_loss', 'General & Administrative'),
  ('473', 'profit_and_loss', 'General & Administrative'),
  ('477', 'profit_and_loss', 'Payroll & People Costs'),
  ('478', 'profit_and_loss', 'Payroll & People Costs'),
  ('479', 'profit_and_loss', 'Payroll & People Costs'),
  ('480', 'profit_and_loss', 'Payroll & People Costs'),
  ('482', 'profit_and_loss', 'Payroll & People Costs'),
  ('483', 'profit_and_loss', 'Payroll & People Costs'),
  ('485', 'profit_and_loss', 'General & Administrative'),
  ('489', 'profit_and_loss', 'Technology & Infrastructure'),
  ('493', 'profit_and_loss', 'General & Administrative'),
  ('494', 'profit_and_loss', 'General & Administrative'),
  ('497', 'profit_and_loss', 'General & Administrative'),
  ('498', 'profit_and_loss', 'General & Administrative'),
  ('499', 'profit_and_loss', 'General & Administrative'),
  ('500', 'profit_and_loss', 'General & Administrative'),
  ('610', 'balance_sheet', 'Current Assets'),
  ('611', 'balance_sheet', 'Current Assets'),
  ('620', 'balance_sheet', 'Current Assets'),
  ('630', 'balance_sheet', 'Current Assets'),
  ('710', 'balance_sheet', 'Fixed Assets'),
  ('711', 'balance_sheet', 'Fixed Assets'),
  ('720', 'balance_sheet', 'Fixed Assets'),
  ('721', 'balance_sheet', 'Fixed Assets'),
  ('740', 'balance_sheet', 'Fixed Assets'),
  ('741', 'balance_sheet', 'Fixed Assets'),
  ('750', 'balance_sheet', 'Fixed Assets'),
  ('751', 'balance_sheet', 'Fixed Assets'),
  ('760', 'balance_sheet', 'Fixed Assets'),
  ('761', 'balance_sheet', 'Fixed Assets'),
  ('764', 'balance_sheet', 'Fixed Assets'),
  ('765', 'balance_sheet', 'Fixed Assets'),
  ('770', 'balance_sheet', 'Fixed Assets'),
  ('771', 'balance_sheet', 'Fixed Assets'),
  ('800', 'balance_sheet', 'Current Liabilities'),
  ('801', 'balance_sheet', 'Current Liabilities'),
  ('803', 'balance_sheet', 'Current Liabilities'),
  ('805', 'balance_sheet', 'Current Liabilities'),
  ('810', 'balance_sheet', 'Current Liabilities'),
  ('811', 'balance_sheet', 'Current Liabilities'),
  ('814', 'balance_sheet', 'Current Liabilities'),
  ('820', 'balance_sheet', 'Current Liabilities'),
  ('825', 'balance_sheet', 'Current Liabilities'),
  ('826', 'balance_sheet', 'Current Liabilities'),
  ('830', 'balance_sheet', 'Current Liabilities'),
  ('835', 'balance_sheet', 'Current Liabilities'),
  ('840', 'balance_sheet', 'Current Liabilities'),
  ('850', 'balance_sheet', 'Current Liabilities'),
  ('855', 'balance_sheet', 'Current Liabilities'),
  ('858', 'balance_sheet', 'Current Liabilities'),
  ('860', 'balance_sheet', 'Current Liabilities'),
  ('868', 'balance_sheet', 'Current Liabilities'),
  ('877', 'balance_sheet', 'Current Liabilities'),
  ('900', 'balance_sheet', 'Long-term Liabilities'),
  ('910', 'balance_sheet', 'Long-term Liabilities'),
  ('920', 'balance_sheet', 'Long-term Liabilities'),
  ('947', 'balance_sheet', 'Current Liabilities'),
  ('950', 'balance_sheet', 'Equity'),
  ('960', 'balance_sheet', 'Equity'),
  ('970', 'balance_sheet', 'Equity'),
  ('980', 'balance_sheet', 'Equity')
) AS v(account_code, statement_type, reporting_category)
WHERE am.account_code = v.account_code;
